version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-retail
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: retaildb
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  airflow:
    build: .
    container_name: airflow-pyspark
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://postgres:postgres@postgres:5432/retaildb"
      AIRFLOW__CORE__FERNET_KEY: "kPeGtqYFKz3v8pZg7edAy34pg8hgfyiF4ESJXHuslz4="
      SPARK_CLASSPATH: "/opt/airflow/jars/postgresql-42.6.0.jar"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./jars:/opt/airflow/jars
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: >
      bash -c "
        airflow db upgrade &&
        airflow users create --username admin --password admin --role Admin --email admin@example.com --firstname Admin --lastname User --if-not-exists &&
        airflow webserver --host 0.0.0.0 --port 8080 &
        airflow scheduler"
